### ISSUE TITLE
Limit file types for upload

### ISSUE THREAD

**Issue by lutzfischer** [colin-combe/CLMS-UI#19]
File types (by extension only)
PeakList/Acquisition:
  - .mgf
  - .msm
  - .apl
  - .zip

Fasta/sequence files:
 - .fasta
 - .txt

Capitalisation should be ignored

**Comment by colin-combe** [comment]
the search submission is a different project... ;) @martingraham

https://github.com/martingraham/searchSubmit

Theres a delay setting up the github account for issue tracking, waiting 
for confirmation from Juri its OK to get organisation account. I think 
its better.

We could still use specific project repo's for lower level code 
discussion. (Keep fork of currently deployed versions of projects in the 
organisation and discuss issues there?)

c


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by lutzfischer** [comment]
recreated the issue under the right project
