### ISSUE TITLE
selecting region on protein bar in xiNET ->  seeing that region highlghted in 3D viewer

### ISSUE THREAD

**Issue by colin-combe** [colin-combe/CLMS-UI#5]
feature request from adam

**Comment by arose** [comment]
@colin-combe I could make a suggestion for that

**Comment by colin-combe** [comment]
On 29/09/15 12:10, Alexander Rose wrote:
>
> @colin-combe <https://github.com/colin-combe> I could make a 
> suggestion for that
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/colin-combe/CLMS-UI/issues/5#issuecomment-144028564>.
>
@arose Yes - I think NGL already has all the functionality needed for 
this, right?

its a short coming on the cross-link viewer side that blocks this. It 
doesn't have the functionality for selecting regions of the bars.

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by colin-combe** [comment]
from Adam - also highlight the links in that region
